###
DELETE http://localhost:8080/products/1
Accept: application/json

###
PUT http://localhost:8080/products/4
Content-Type: application/json

{
  "name": "12",
  "brand": "iphone"
}

###
GET http://localhost:8080/products/4
Accept: application/json

###
POST http://localhost:8080/products/
Content-Type: application/json

{
  "name": "11",
  "brand": "iphone"
}


###
