POST http://localhost:8080/orders/
Content-Type: application/json

{
  "title": "smartphones for days"
}
###

POST http://localhost:8080/products/
Content-Type: application/json

{
  "name": "12",
  "brand": "iphone",
  "order": {
    "id": 1
  }
}
###
GET http://localhost:8080/orders/1
#
####
GET http://localhost:8080/products/2
